version: "3.8"

networks:
  api_network:

services:
  api:
    build: .
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - $PORT:$PORT
    restart: always
    networks:
      - api_network

  postgres:
    image: postgres:alpine
    command: -p $POSTGRES_PORT
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - api_network
